PracticeApp/Models/Budget.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;


namespace PracticeApp.Models
{
    public class Budget
    {
        [Key]
        public string Id { get; set; }
        [ForeignKey("UserId")]
        public IdentityUser User { get; set; }

        [Display(Name = "Gross Salary")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal GrossSalary { get; set; }

        [Display(Name = "Net Salary")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal NetSalary { get; set; }

        [Display(Name = "Additional Income")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal AdditionalIncome { get; set; }

        [Display(Name = "Total Monthly Income")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal TotalIncome { get; set; }

        [Display(Name = "Housing Expenses")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal HousingExpense { get; set; }

        [Display(Name = "Utilities Expenses")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal UtilitiesExpense { get; set; }

        [Display(Name = "Food Expenses")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal FoodExpense { get; set; }

        [Display(Name = "Debt Expenses")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal DebtExpense { get; set; }

        [Display(Name = "Additional Expenses")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal AdditionalExpense { get; set; }

        [Display(Name = "Total Expenses")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public Decimal TotalExpenses { get; set; }
    }
}

PracticeApp/Controllers/BudgetController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PracticeApp.Data;
using PracticeApp.Models;
using System.Security.Claims;

namespace PracticeApp.Controllers
{
    public class BudgetController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public BudgetController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Budget
        public async Task<IActionResult> Index()
        {
            return View(await _context.Budget.ToListAsync());
        }

        // GET: Budget/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var budget = await _context.Budget
                .FirstOrDefaultAsync(m => m.Id == id);
            if (budget == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            if (budget.User != user)
            {
                return NotFound();
            }

            return View(budget);
        }

        // GET: Budget/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Budget/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,User,GrossSalary,NetSalary,AdditionalIncome,TotalIncome,HousingExpense,UtilitiesExpense,FoodExpense,DebtExpense,AdditionalExpense,TotalExpenses")] Budget budget)
        {
            if (ModelState.IsValid)
            {
                budget.Id = Guid.NewGuid().ToString();
                budget.User = await _userManager.GetUserAsync(User);
                _context.Add(budget);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { budget.Id });
            }
            return View(budget);
        }

        // GET: Budget/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var budget = await _context.Budget.FirstOrDefaultAsync(m => m.Id == id);
            if (budget == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(User);
            if (budget.User != user)
            {
                return NotFound();
            }
            return View(budget);
        }

        // POST: Budget/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,User,GrossSalary,NetSalary,AdditionalIncome,TotalIncome,HousingExpense,UtilitiesExpense,FoodExpense,DebtExpense,AdditionalExpense,TotalExpenses")] Budget budget)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(budget);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BudgetExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { budget.Id });
            }
            return View(budget);
        }

        // GET: Budget/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var budget = await _context.Budget
                .FirstOrDefaultAsync(m => m.Id == id);
            if (budget == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);
            if (budget.User != user)
            {
                return NotFound();
            }

            return View(budget);
        }

        // POST: Budget/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var budget = await _context.Budget.FindAsync(id);
            _context.Budget.Remove(budget);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Create));
        }

        private bool BudgetExists(string id)
        {
            return _context.Budget.Any(e => e.Id == id);
        }
    }
}

PracticeApp/Controllers/PriorityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PracticeApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PracticeApp.Controllers
{
    public class PriorityController : Controller
    {
        private readonly ILogger<PriorityController> _logger;

        public PriorityController(ILogger<PriorityController> logger)
        {
            _logger = logger;
        }

        public IActionResult PriorityPath()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PracticeApp/Views/Budget/Create.cshtml
@model PracticeApp.Models.Budget

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-lg-center">
    <h1 class="align-content-lg-center pb-3">Create A Budget</h1>
</div>
    <hr />
    <div class="row justify-content-lg-center">
        <div class="col-lg-4 text-lg-center h4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="GrossSalary" class="control-label"></label>
                    <input asp-for="GrossSalary" id="grossSalary" class="form-control" pattern="^\d{1,3}(,\d{3})*(\.\d+)?$" data-type="currency" value="" />
                    <span asp-validation-for="GrossSalary" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NetSalary" class="control-label"></label>
                    <input asp-for="NetSalary" id="netSalary" class="form-control" pattern="^\d{1,3}(,\d{3})*(\.\d+)?$" data-type="currency" value="" />
                    <span asp-validation-for="NetSalary" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdditionalIncome" class="control-label"></label>
                    <input asp-for="AdditionalIncome" id="extraIncome" class="form-control" pattern="^\d{1,3}(,\d{3})*(\.\d+)?$" data-type="currency" value="" />
                    <span asp-validation-for="AdditionalIncome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TotalIncome" class="control-label"></label>
                    <input asp-for="TotalIncome" id="totalIncome" class="form-control-plaintext" pattern="^\d{1,3}(,\d{3})*(\.\d+)?$" data-type="currency" value="" readonly />
                    <span asp-validation-for="TotalIncome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="HousingExpense" class="control-label"></label>
                    <input asp-for="HousingExpense" id="housingExpense" class="form-control" pattern="^\d{1,3}(,\d{3})*(\.\d+)?$" data-type="currency" value="" />
                    <span asp-validation-for="HousingExpense" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UtilitiesExpense" class="control-label"></label>
                    <input asp-for="UtilitiesExpense" id="utilitiesExpense" class="form-control" pattern="^\d{1,3}(,\d{3})*(\.\d+)?$" data-type="currency" value="" />
                    <span asp-validation-for="UtilitiesExpense" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FoodExpense" class="control-label"></label>
                    <input asp-for="FoodExpense" id="foodExpense" class="form-control" pattern="^\d{1,3}(,\d{3})*(\.\d+)?$" data-type="currency" value="" />
                    <span asp-validation-for="FoodExpense" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DebtExpense" class="control-label"></label>
                    <input asp-for="DebtExpense" id="debtExpense" class="form-control" pattern="^\d{1,3}(,\d{3})*(\.\d+)?$" data-type="currency" value="" />
                    <span asp-validation-for="DebtExpense" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AdditionalExpense" class="control-label"></label>
                    <input asp-for="AdditionalExpense" id="extraExpense" class="form-control" pattern="^\d{1,3}(,\d{3})*(\.\d+)?$" data-type="currency" value="" />
                    <span asp-validation-for="AdditionalExpense" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TotalExpenses" class="control-label"></label>
                    <input asp-for="TotalExpenses" id="totalExpense" class="form-control-plaintext" readonly="readonly" pattern="^\d{1,3}(,\d{3})*(\.\d+)?$" data-type="currency" value="" />
                    <span asp-validation-for="TotalExpenses" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-controller="Priority" asp-action="PriorityPath">Back to Flowchart</a>
    </div>

    <script>
        // Jquery Dependency

        $("input[data-type='currency']").on({
            keyup: function () {
                formatCurrency($(this));
            },
            blur: function () {
                formatCurrency($(this), "blur");
            }
        });


        function formatNumber(n) {
            // format number 1000000 to 1,234,567
            return n.replace(/\D/g, "").replace(/\B(?=(\d{3})+(?!\d))/g, ",")
        }


        function formatCurrency(input, blur) {
            // appends $ to value, validates decimal side
            // and puts cursor back in right position.

            // get input value
            var input_val = input.val();

            // don't validate empty input
            if (input_val === "") { return; }

            // original length
            var original_len = input_val.length;

            // initial caret position
            var caret_pos = input.prop("selectionStart");

            // check for decimal
            if (input_val.indexOf(".") >= 0) {

                // get position of first decimal
                // this prevents multiple decimals from
                // being entered
                var decimal_pos = input_val.indexOf(".");

                // split number by decimal point
                var left_side = input_val.substring(0, decimal_pos);
                var right_side = input_val.substring(decimal_pos);

                // add commas to left side of number
                left_side = formatNumber(left_side);

                // validate right side
                right_side = formatNumber(right_side);

                // On blur make sure 2 numbers after decimal
                if (blur === "blur") {
                    right_side += "00";
                }

                // Limit decimal to only 2 digits
                right_side = right_side.substring(0, 2);

                // join number by .
                input_val = left_side + "." + right_side;

            } else {
                // no decimal entered
                // add commas to number
                // remove all non-digits
                input_val = formatNumber(input_val);
                input_val = input_val;

                // final formatting
                if (blur === "blur" || blur === "change") {
                    input_val += ".00";
                }
            }

            // send updated string to input
            input.val(input_val);

            // put caret back in the right position
            var updated_len = input_val.length;
            caret_pos = updated_len - original_len + caret_pos;
            input[0].setSelectionRange(caret_pos, caret_pos);
        }
        $(document).ready(function () {

            // You can't calculate the answer as soon as the page is ready.
            // You need to wait until the user has done something that triggers
            // the calculation. Here, it will happen as the user types into either
            // of the first two inputs
            $("#grossSalary, #netSalary, #extraIncome").on("input", calcIncome);
            $("#housingExpense, #utilitiesExpense, #foodExpense, #debtExpense, #extraExpense").on("input", calcExpense);
            function calcIncome() {
                var sal = $("#netSalary").val().replace(/,/g, '');
                var ext = $("#extraIncome").val().replace(/,/g, '');
                $("#totalIncome").val(parseFloat(sal) + parseFloat(ext));
                formatCurrency($("#totalIncome"), "change");
            }
            function calcExpense() {
                var house = $("#housingExpense").val().replace(/,/g, '');
                var util = $("#utilitiesExpense").val().replace(/,/g, '');
                var food = $("#foodExpense").val().replace(/,/g, '');
                var debt = $("#debtExpense").val().replace(/,/g, '');
                var ext = $("#extraExpense").val().replace(/,/g, '');
                $("#totalExpense").val(parseFloat(house) + parseFloat(util) + parseFloat(food) + parseFloat(debt) + parseFloat(ext));
                formatCurrency($("#totalExpense"), "change");
            }
        });
    </script>

PracticeApp/Views/Budget/Delete.cshtml
@model PracticeApp.Models.Budget

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Budget</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GrossSalary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GrossSalary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NetSalary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NetSalary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalIncome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AdditionalIncome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalIncome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalIncome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HousingExpense)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HousingExpense)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UtilitiesExpense)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UtilitiesExpense)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FoodExpense)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FoodExpense)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DebtExpense)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DebtExpense)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalExpense)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AdditionalExpense)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalExpenses)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalExpenses)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PracticeApp/Views/Budget/Details.cshtml
@model PracticeApp.Models.Budget

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Budget</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GrossSalary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GrossSalary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NetSalary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NetSalary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalIncome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AdditionalIncome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalIncome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalIncome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HousingExpense)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HousingExpense)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UtilitiesExpense)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UtilitiesExpense)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FoodExpense)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FoodExpense)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DebtExpense)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DebtExpense)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AdditionalExpense)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AdditionalExpense)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TotalExpenses)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TotalExpenses)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
    <a asp-controller="Priority" asp-action="PriorityPath">Back to Flowchart</a>
</div>

PracticeApp/Views/Budget/Edit.cshtml
@model PracticeApp.Models.Budget

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Budget</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="GrossSalary" class="control-label"></label>
                <input asp-for="GrossSalary" class="form-control" />
                <span asp-validation-for="GrossSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NetSalary" class="control-label"></label>
                <input asp-for="NetSalary" class="form-control" />
                <span asp-validation-for="NetSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalIncome" class="control-label"></label>
                <input asp-for="AdditionalIncome" class="form-control" />
                <span asp-validation-for="AdditionalIncome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalIncome" class="control-label"></label>
                <input asp-for="TotalIncome" class="form-control" />
                <span asp-validation-for="TotalIncome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HousingExpense" class="control-label"></label>
                <input asp-for="HousingExpense" class="form-control" />
                <span asp-validation-for="HousingExpense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UtilitiesExpense" class="control-label"></label>
                <input asp-for="UtilitiesExpense" class="form-control" />
                <span asp-validation-for="UtilitiesExpense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FoodExpense" class="control-label"></label>
                <input asp-for="FoodExpense" class="form-control" />
                <span asp-validation-for="FoodExpense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DebtExpense" class="control-label"></label>
                <input asp-for="DebtExpense" class="form-control" />
                <span asp-validation-for="DebtExpense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdditionalExpense" class="control-label"></label>
                <input asp-for="AdditionalExpense" class="form-control" />
                <span asp-validation-for="AdditionalExpense" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalExpenses" class="control-label"></label>
                <input asp-for="TotalExpenses" class="form-control" />
                <span asp-validation-for="TotalExpenses" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PracticeApp/Views/Budget/Index.cshtml
@model IEnumerable<PracticeApp.Models.Budget>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GrossSalary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdditionalIncome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalIncome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HousingExpense)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UtilitiesExpense)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FoodExpense)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DebtExpense)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdditionalExpense)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalExpenses)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GrossSalary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdditionalIncome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalIncome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HousingExpense)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UtilitiesExpense)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FoodExpense)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DebtExpense)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdditionalExpense)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalExpenses)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>